config/routes.rb
Rails.application.routes.draw do
 root 'pages#home'
 get 'about', to:'pages#about'
 resources :articles 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 4, maximum:100}
  validates :description, presence: true, length: {minimum: 6, maximum: 400}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:edit,:update,:destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save 
      flash[:notice] = "Article was saved successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] ="Article updated"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article deleted"
      redirect_to articles_path
    else
      redirect_to articles_path
    end

  end

  private 

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title,:description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<%end%>

<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end%>

app/views/articles/edit.html.erb
<h1>Edit the article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>


<table>
  <thead>
    <th>Title</th>
    <th>Description</th>
    <th colspan="3">Action</th>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title%></td>
      <td><%= article.description %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<button type="button"><%= link_to 'New Article', new_article_path %></button>

app/views/articles/new.html.erb
<h1>create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title : </strong> <%=@article.title%></p>
<p><strong>Description: </strong> <%=@article.description%> </p>

<button type="button"><%= link_to 'Edit Article', edit_article_path %></button>
<button type="button"><%= link_to 'Delete Article', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %></button>
<button type="button"><%= link_to 'Go to Main', articles_path %></button>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <%= msg %>
<%end%>
<%= yield %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
  </body>
</html>

app/views/pages/about.html.erb
<center><h1>About us</h1></center>

app/views/pages/home.html.erb
<title>Alpha Blog</title>
<h1>Welcome to the Alpha Blog</h1>
<h2>where creativity rules</h2>
<p>i am adding it to production</p>